### ISSUE TITLE
Disambiguation with unions fails

### ISSUE THREAD

**Issue by jlapeyre** [wesselb/plum#1]
I get the following (on master 7e9b8657)
```python
from plum import dispatch

@dispatch
def f(x: {object, int}, y: int):
    return x + y

@dispatch
def f(x: int, y: object):
    return x * y

print(f(3, 3.0)) # 9.0
print(f(3.0, 3)) # 6.0
print(f(3, 3)) # Should be 6. Error, fails to disambiguate
```

The multipledispatch library *does* correctly dispatch in this case. I don't know if this is a bug here, or it's not intended to be supported.

**Comment by wesselb** [comment]
Hey @jlapeyre! Thanks for your interest in the package.

I agree that it totally isn't obvious from the README, but `master` is current a WIP. (I'll add a notice.) There are a few kinks which need to be worked out, but it's been a bit busy lately, so haven't gotten around to fixing those. I hope to release the new version within the next week, which should be free of bugs like this.

I refer to the [latest release](https://github.com/wesselb/plum/releases/tag/v0.2.5) with the corresponding [latest docs](https://wesselb.github.io/plum), which should work without any problems.

**Comment by wesselb** [comment]
On the current master, the above snippet gives an ambiguity error.

```python
AmbiguousLookupError: For function "f", signature (builtins.int, builtins.int) is ambiguous among the following:
  ({builtins.int, builtins.object}, builtins.int) (precedence: 0)
  (builtins.int, builtins.object) (precedence: 0)
```

Are you sure that `f(3, 3)` should be `6`?

Compare with the following Julia code:

```julia
julia> f(x::Union{Any, Int}, y::Int) = x + y
f (generic function with 1 method)

julia> f(x::Int, y::Any) = x * y
f (generic function with 2 methods)

julia> f(3, 3)
ERROR: MethodError: f(::Int64, ::Int64) is ambiguous. Candidates:
  f(x, y::Int64) in Main at REPL[1]:1
  f(x::Int64, y) in Main at REPL[2]:1
```

If, by `f(x: {object, int}, y: int)`, you mean to implement the methods `f(x: object, y:int)` _and_ `f(x: int, y: int)`, then you should write the following:

```python
from plum import dispatch

@dispatch.multi((object, int), (int, int))
def f(x: {object, int}, y: int):
    return x + y

@dispatch
def f(x: int, y: object):
    return x * y
```

```python
>>> f(3, 3)
6
```

Why does the ambiguity error happen? Well, since `int` is a subclass of `object`, `{int, object} == object`:
```python
>>> from plum import Union, Type

>>> Union(int, object) == Type(object)
True
```

Compare with the following Julia code:
```julia
julia> Union{Any, Int} == Any
true
```

**Comment by jlapeyre** [comment]
Thanks for the detailed responses. 

> but `master` is current a WIP

I somehow was finding a mix of documentation, and was lead to `master` in order to get examples to work.

Of course you are correct about the meaning of `Union`. I was lead astray because I came from multipledispatch, which has different semantics:
```python
from multipledispatch import dispatch

@dispatch((object, int), int)
def f(x, y):
    return x + y

@dispatch(int, object)
def f(x, y):
    return x * y

print(f(3, 3.0)) # 9.0
print(f(3.0, 3)) # 6.0
print(f(3, 3)) # 6
```

Hmm, I tried `@dispatch.multi` and didn't get what I was looking for. I'll revisit it.

**Comment by jlapeyre** [comment]
In your example
```python
@dispatch.multi((object, int), (int, int))
def f(x: {object, int}, y: int):
    return x + y
```
Can I assume that semantics of the set `{object, int}` is the same as when it appears under plain `@dispatch`, that is, the set represents a union type? At least in your example, I get the same behavior if I instead have
```python
@dispatch.multi((object, int), (int, int))
def f(x: object, y: int):
    return x + y
```

**Comment by wesselb** [comment]
@jlapeyre, perhaps it is a bit misleading, but in the snippet with `@dispatch.multi` the type hints are not used. Instead, the dispatcher uses the "collection of signatures" that you pass to `@dispatch.multi`. If you like, you can omit the type hints:

```
@dispatch.multi((object, int), (int, int))
def f(x, y):
    return x + y
```

I added them for the sake of completeness and to help linters of IDEs.

**Comment by jlapeyre** [comment]
> What is the behaviour that you are looking for? 

Just for completeness, this has been continued in #3
