### ISSUE TITLE
Accept `None` as type annotation

### ISSUE THREAD

**Issue by ruancomelli** [wesselb/plum#13]
Hi! Thank you so much for this library, I've been looking for something like this for a long time!

I would like to suggest accepting `None` as a valid type in Plum. For instance, this snippet does not work:
```py
from plum import dispatch

def foo(x: None) -> None:
    return x

print(foo(None)) # raises: RuntimeError: Could not convert "None" to a type.
```
whereas this one works as expected:
```py
from plum import dispatch

NoneType = type(None)

@dispatch
def foo(x: NoneType) -> NoneType:
    return x

print(foo(None)) # prints: None
```
Since type-annotating `None`'s type as `None` is the standard way to do it, I think this simple enhancement would make dispatching a lot more intuitive in this case.

I would also love to submit a PR if you agree, I'm just not familiar with Plum's implementation. It seems to me that adding
```py
if obj is None:
    return Type(type(None))
```
just [before the RuntimeError](https://github.com/wesselb/plum/blob/516e4aa75910abcfd7a510726c586600b9edfd6e/plum/type.py#L364) should fix this, am I correct?

**Comment by wesselb** [comment]
Hey @ruancomelli, I'm very glad to hear that the library is useful for you. :)

> Since type-annotating None's type as None is the standard way to do it, I think this simple enhancement would make dispatching a lot more intuitive in this case.

I fully agree!

> I would also love to submit a PR if you agree, (...) am I correct?

And you're also totally right. :) A PR would be fantastic; please do open one!
