### ISSUE TITLE
[FR] Add a way to define a function (whitout defining a method)

### ISSUE THREAD

**Issue by PhilipVinc** [wesselb/plum#16]
AKA, I'd like the equivalent of Julia's

```julia
"""
docstring
"""
function test end
```

so that I can more easily organize my code.

Also i am trying to make my code more functional, but for backward compatibility sometimes I have patterns like this
```python
class A:
   def kron(self, other):
        kron(self, other)
...

@dispatch
def kron(a: A, b:A):
   ..

@dispatch
def kron(a:A, b:B)
  ..
```

in which case, again, being able to define a function with no methods would be great.

**Comment by PhilipVinc** [comment]
I think this should do it, at least for non-class functions

```python
def define(function):
	"""
	Define a function using plum's multiple-dispatch
	"""
	fname = function.__name__

	if fname in plum._functions:
		raise ValueError(f"Cannot redefine already-existing function {fname}")

	return _plum.Function(function)
```

**Comment by wesselb** [comment]
Hey! In the newest release, `v1.3.2`, the following is possible:

```python
from plum import dispatch

@dispatch.abstract
def f(x):
    """Important function."""
```

```python
>>> f
<function <function f at 0x7fbf30d21ea0> with 0 method(s)>
```

This works for normal functions and also works in classes.
