### ISSUE TITLE
Readme ambiguity: dispatch first or last decorator

### ISSUE THREAD

**Issue by heetbeet** [wesselb/plum#22]
The readme doesn't match its example in the following case:

![Screenshot_20210717_182602](https://user-images.githubusercontent.com/4103775/126043473-181843a3-fb6e-4793-b35a-da477d4c4d91.jpg)

**Comment by wesselb** [comment]
Hey @heetbeet! You're totally right that the README is ambiguous there. It should say "outermost" instead of last "last". Thank you for raising this issue. :)
