### ISSUE TITLE
Support for pandas.core.series.Series type

### ISSUE THREAD

**Issue by pengguanya** [wesselb/plum#24]
I am trying to dispatch on class pandas.core.series.Series with code like, 
```
import pandas as pd
@dispatch
def foo(x: Union[list, tuple, pd.core.series.Series]) -> str:
    ...
```

and I got error:
`plum.function.NotFoundLookupError: For function "_quote", signature Signature(pandas.core.series.Series) could not be resolved.`

It seems panas.core.series.Series is not considered as a class/type to be dispatch on. Can it be implemented? Or, it is there, but my code was wrong?

**Comment by pengguanya** [comment]
this might related to something else. I will check and confirm

**Comment by PhilipVinc** [comment]
I just tried and it works.

**Comment by wesselb** [comment]
Yes, I think this should just work. @pengguanya let us know if you can't manage to figure it out!
