### ISSUE TITLE
Default values might be broken

### ISSUE THREAD

**Issue by wesselb** [wesselb/plum#29]
See https://github.com/wesselb/stheno/issues/14. Not entirely sure why this is breaking, but certainly something is wrong.

**Comment by wesselb** [comment]
The pattern that's broken which worked with the previous behaviour is

```python
from plum import dispatch

class A:
    @dispatch
    def __init__(self, x, y, z=1):
        print(x, y, z)

    @dispatch
    def __init__(self, y, z=1):
        self.__init__(42, y, z=z)
```

```python
>>> A(2)
TypeError: __init__() got multiple values for argument 'z'
```

The problem is that the two-argument method from the first `__init__` is overwritten by the automatically generated default of the second `__init__`. For example, reversing the order of the methods fixes this:

```python
from plum import dispatch

class A:
    @dispatch
    def __init__(self, y, z=1):
        self.__init__(42, y, z=z)

    @dispatch
    def __init__(self, x, y, z=1):
        print(x, y, z)
```

```python
>>> A(2)
42 2 1
```

@PhilipVinc, should we change the behaviour to only add automatically generated default methods if those don't exist yet?

**Comment by PhilipVinc** [comment]
I'm on a train, and I can't seem to download the dependencies so I can't test it right now.

However...

It seems to me that 
```
__init__(self, mean, kernel, measure=None, name=None):
```
emits 3 methods like
```
__init__(self, mean, kernel)
__init__(self, mean, kernel, measure)
__init__(self, mean, kernel, measure, name)
```

and 
```python
__init__(self, kernel, measure=None, name=None):
```
emits
```
__init__(self, kernel)
__init__(self, kernel, measure)
__init__(self, kernel, measure, name)
```

Since they are all untyped this is messing something up... let me see...

**Comment by PhilipVinc** [comment]
Ah, seems you already figured it out.

> @PhilipVinc, should we change the behaviour to only add automatically generated default methods if those don't exist yet? Or do we accept this as the intended behaviour?

I hate to break code, and I'd try to avoid this if possible.

However, while thinking about it I think that both plum *and* the code have an issue?

Trying to run your example in Julia (which I like to think we are following) yields:

```julia
julia> function f(x, y,z=1)
          @info "f2" x y z
          print("$x $y $z")
       end
f (generic function with 2 methods)

julia> methods(f)
# 2 methods for generic function "f":
[1] f(x, y) in Main at REPL[1]:1
[2] f(x, y, z) in Main at REPL[1]:1

julia> function f(y,z=1)
          @info "f1" y z
          f(42, y, z)
       end
f (generic function with 3 methods)

julia> methods(f)
# 3 methods for generic function "f":
[1] f(y) in Main at REPL[2]:1
[2] f(y, z) in Main at REPL[2]:1
[3] f(x, y, z) in Main at REPL[1]:1

julia> f(2)
┌ Info: f1
│   y = 2
└   z = 1
┌ Info: f2
│   x = 42
│   y = 2
└   z = 1
42 2 1
julia> f(2, 3)
┌ Info: f1
│   y = 2
└   z = 3
┌ Info: f2
│   x = 42
│   y = 2
└   z = 3
42 2 3
julia> f(2, 3, 4)
┌ Info: f2
│   x = 2
│   y = 3
└   z = 4
2 3 4
```

and if you swap the order of the two method definitions you get
```julia 
julia> f(2)
┌ Info: f2
│   x = 2
│   y = 1
└   z = 1
2 1 1
julia> f(2, 3)
┌ Info: f2
│   x = 2
│   y = 3
└   z = 1
2 3 1
julia> f(2, 3, 4)
┌ Info: f2
│   x = 2
│   y = 3
└   z = 4
2 3 4
```

So the code itself is a bit fishy: the latter default-method overwrites the former method...

**Comment by PhilipVinc** [comment]
I think we should match Julia's behaviour in this regard, maybe throw a warning saying that a method/signature was overwritten.

(I think in general it is best to overwrite + maybe warn than not overwrite the method definition?)

What do you think?

**Comment by wesselb** [comment]
> I think we should match Julia's behaviour in this regard, maybe throw a warning saying that a method/signature was overwritten.

Thanks for checking Julia's behaviour—that's a good check. I agree that we should try to match Julia as closely as possible, so let's keep it as it is. I can imagine that only writing non-existing automatically generated default methods can introduce other subtle edge cases and bugs, and would only make the control flow more complicated, so maybe that's a bad idea in itself.

> However, while thinking about it I think that both plum and the code have an issue?

The code indeed has an issue. I've not consistently typed arguments with default values, which is now biting me in the ass. As you say, the fix is easy: add types.

Okay, it looks like everything is fine after all. :) Thanks for helping out so quickly, @PhilipVinc! Closing this now.

**Comment by PhilipVinc** [comment]
However, I'm not sure following Julia would help... Python allows to call with a keyword all positional arguments.

Starting in python 3.8, it is possible to mark arguments as positional only. We could use this, but I'm not sure it's possible to support it pre-3.8...
```python
>>> def f(x,y, /, *, z=3):
...   print(x,y,z)
...
>>> f(x=1, y=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: f() got some positional-only arguments passed as keyword arguments: 'x, y'
```

Otherwise is it possible to make the signature logic smarter and actually understand positional-and-keyword arguments?

**Comment by wesselb** [comment]
> However, I'm not sure following Julia would help...

Hmm, do you mean that we should support the above pattern? I could live with "writing a method with default values is equivalent to writing multiple methods", which we can clearly state in the manual. As a consequence, the above pattern is then something you just shouldn't do. If you really wanted to, you could do it this way:

```python
from plum import dispatch

class A:
    @dispatch
    def __init__(self, x, y, *, z=1):
        print(x, y, z)

    @dispatch
    def __init__(self, y, *, z=1):
        self.__init__(42, y, z=z)
```

which forces `z` to be a keyword-only argument.

```python
>>> A(2)
42 2 1
```

**Comment by PhilipVinc** [comment]
I mean that the original pattern (without kw-only) in plum gives an error, while in Julia it works (though you have to be careful about redefining the method).

I don't yet understand completely why it raises an error...

**Comment by wesselb** [comment]
I think the pattern also gives an error in Julia:

```julia
julia> f(x, y, z=1) = @show x y z
f (generic function with 2 methods)

julia> f(y, z=1) = f(42, y, z=z)
f (generic function with 3 methods)

julia> f(2)
ERROR: MethodError: no method matching f(::Int64, ::Int64; z=1)
Closest candidates are:
  f(::Any, ::Any) at REPL[2]:1 got unsupported keyword argument "z"
  f(::Any, ::Any, ::Any) at REPL[1]:1 got unsupported keyword argument "z"
  f(::Any) at REPL[2]:1 got unsupported keyword argument "z"
Stacktrace:
 [1] f(y::Int64, z::Int64) (repeats 2 times)
   @ Main ./REPL[2]:1
 [2] top-level scope
   @ REPL[3]:1

```

The catch is that `f(42, y, z=z)` is called with `z=z`, rather than as `f(42, y, z)`.

If you call it as `f(42, y, z)`, then Python produces an output simlar to Julia's:

```python
from plum import dispatch

class A:
    @dispatch
    def __init__(self, x, y, z=1):
        print(x, y, z)

    @dispatch
    def __init__(self, y, z=1):
        self.__init__(42, y, z)
```

```python
>>> A(2)
42 2 1
```

**Comment by PhilipVinc** [comment]
Yes, but in Python/plum it is failing with error 
```
>>> A(2)
TypeError: __init__() got multiple values for argument 'z'
```

which means that it's passing z twice, probably once positionally and once with the keyword.
this should not happen..

**Comment by wesselb** [comment]
> which means that it's passing z twice, probably once positionally and once with the keyword.

Ah, yeah, I think (and that's probably what you pointed out earlier) that's because Python the call is something like `(lambda y, z=1)(42, y, z=z)`, which means means that `z` is given twice (once positionally by `y` and once with the keyword `z=z`). Julia appears to interpret the superfluous `z=z` as a keyword argument which does not exist.

**Comment by PhilipVinc** [comment]
Yeah. 
It is because for plum, now, arguments are either positional or keyword when dispatching.

But then when plum calls the function itself, nothing prevents python prom interpreting the kwargs as positional arguments.

We could make plum error when a keyword arg matches a positional argument in the signature.
but that might slow down dispatch a bit...

**Comment by PhilipVinc** [comment]
We could also manipulate the function when we register it, and 'insert' a `\` to mark arguments as positional only, but that would only work on 3.8.

**Comment by wesselb** [comment]
Right, that would indeed improve the error:

```python
>>> (lambda y, z=1, /: None)(42, 2, z=1)
TypeError: <lambda>() got some positional-only arguments passed as keyword arguments: 'z'
```

We could make this change for Python 3.8+ only, and keep the error as it is for Python 3.6?

**Comment by PhilipVinc** [comment]
apparently `/` is ignored in 3.6 and 3.7 so it can be used without breaking code, which is good.

I just need to find exactly how to manipulate the function definition and mark arguments as positional only even if the supplied function does not mark them.

I think we should basically find `*` which marks kw-only arguments, and insert a `/` right before.

**Comment by wesselb** [comment]
> apparently / is ignored in 3.6 and 3.7 so it can be used without breaking code, which is good.

Ah, sweet! That should be easy then. Let me put together a PR in the next few days and tag you for review.
