### ISSUE TITLE
NotFoundLookupError when using dispatch.multi in class method

### ISSUE THREAD

**Issue by jlapeyre** [wesselb/plum#3]
master 7e9b8657

```python
from plum import dispatch

@dispatch.multi((int, str), (int, int))
def f(x: int, y: {int, str}):
    print(f'{x}, {y}')

class C():
    @dispatch
    def g(self, x: int, y: int):
        print(f'{x}, {y}')

    @dispatch
    def g(self, x: int, y: str):
        print(f'{x}, {y}')

    @dispatch.multi((int, str), (int, int))
    def h(self, x: int, y: {int, str}):
        print(f'{x}, {y}')

f(3, 4) # OK

c = C()
c.g(3, 4) # OK
c.g(3, 'cat') # OK

c.h(3, 4) # NotFoundLookupError
c.h(3, 'cat') # NotFoundLookupError
```

I did not yet try this on the latest released branch.

**Comment by wesselb** [comment]
If you'd like to use inheritance, you need to use some additional machinery:

```python
from plum import Dispatcher, Referentiable, Self, dispatch

@dispatch.multi((int, str), (int, int))
def f(x: int, y: {int, str}):
    print(f'{x}, {y}')

class C(Referentiable):
    dispatch = Dispatcher(in_class=Self)

    @dispatch
    def g(self, x: int, y: int):
        print(f'{x}, {y}')

    @dispatch
    def g(self, x: int, y: str):
        print(f'{x}, {y}')

    @dispatch.multi((int, str), (int, int))
    def h(self, x: int, y: {int, str}):
        print(f'{x}, {y}')

f(3, 4) # OK

c = C()
c.g(3, 4)
c.g(3, 'cat')

c.h(3, 4)
c.h(3, 'cat')
```

```python
3, 4
3, 4
3, cat
3, 4
3, cat
```

This is described [here](https://github.com/wesselb/plum#inheritance).

**Comment by jlapeyre** [comment]
Thanks, this seems to work. I had read that section on inheritance, but  I don't understand why it applies here. My example does not use inheritance, right? Except insofar as `C` inherits from `object`. If they were plain functions, the two methods for `g` should be equivalent to the multiple-method definition of `h`, and in fact the code works that way. As class methods, should not the two methods for `g` be equivalent to those in the single definition of  `h`?

I'll try using `Dispatcher, Referentiable, Self`. The class in my application inherits from a long chain that ultimately inherits from ABC. I'll have to figure out how to combine these.

**Comment by wesselb** [comment]
Ah, sorry, I should have said that this should also be used when classes are used, even if you don't make use of inheritance. The problem is that vanilla functions and method of classes behave slightly differently.

Plum should play nicely with ABC. Here's an example:

```python
import abc

from plum import Dispatcher, Referentiable, Self

class A(metaclass=Referentiable(abc.ABCMeta)):
    @abc.abstractmethod
    def f(self, x):
        pass

class B(A):
    _dispatch = Dispatcher(in_class=Self)

    @_dispatch
    def f(self, x: int):
        return x
```

```python
>>> A()
TypeError: Can't instantiate abstract class A with abstract methods f

>>> b = B()

>>> b.f(1)
1

>>> b.f("1")
NotFoundLookupError: For function "f" of <class '__main__.B'>, signature (builtins.str) could not be resolved.
```

**Comment by jlapeyre** [comment]
Thanks. Your last example has solved my problem.

**Comment by wesselb** [comment]
Perfect! Very glad to hear that.
