### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by lgblkb** [wesselb/plum#36]
Any possible support for applying plum dispatch on async methods?

**Comment by wesselb** [comment]
@lgblkb could you give an example of what you would like to achieve?

Plum should already work with async methods, as illustrated in the following [simple example](https://stackoverflow.com/questions/50757497/simplest-async-await-example-possible-in-python):

```python
import asyncio
from plum import dispatch


@dispatch
async def io_related(name: str):
    print(f"{name} started")
    await asyncio.sleep(1)
    print(f"{name} finished")


async def main():
    await asyncio.gather(
        io_related("first"),
        io_related("second"),
    )


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by lgblkb** [comment]
Thanks! That's all I need. Cool.
