### ISSUE TITLE
Tag a new release on PyPi?

### ISSUE THREAD

**Issue by PhilipVinc** [wesselb/plum#4]
Hi!
I recently discovered your package and really like it.

I've seen you have recently added support for inheriting the dispatch types from the type annotations. That's very nice!
As I'd like to use it in one of my packages, could you tag a new release on PyPi?

Thanks!

**Comment by wesselb** [comment]
Hey @PhilipVinc!

I'm very glad to hear that you like the package! The current `master` still has a few kinks to work out, which is what I'm currently working on. I hope to push a new release to PyPi within the next 7 days. :)

**Comment by wesselb** [comment]
Hey @PhilipVinc!

I've just tagged a new release on PyPI, so closed this issue.
