### ISSUE TITLE
[FR] Support 'typing.Any' as a fallback

### ISSUE THREAD

**Issue by PhilipVinc** [wesselb/plum#5]
Support a default method fallback with signature 'Any' or when no signature is defined.

This is usefull for defining functions like
```python
@dispatch
def is_fancy_object(x)
   return False

@dispatch
def is_fancy_object(x: MyFancyClass)
  return True
```

which is a common pattern in Julia

**Comment by PhilipVinc** [comment]
I would argue that by default you plum should treat non-annotated types as Any.

Then (but there I am not 100% sure) I think that in python every object inherits from `object`? So a possible way to go would be to just translate Any to object. Though I'm not sure this is correct...

**Comment by wesselb** [comment]
Hey @PhilipVinc,

With the most recent push to `master`, I've added support for `typing.Any`. `typing.Any` is synonomous with `object`, which is the default value if no type hint is set.
