### ISSUE TITLE
dispatch decorator in __init_subclass__

### ISSUE THREAD

**Issue by rustrar** [wesselb/plum#52]
Hi!
I want to apply the `@dispatch` decorator to method in child class. 
I can't edit the child class, so I try to apply the decorator in the `__init_subclass__` method 
When I try to run the test, it throws an error _`plum.resolvable.ResolutionError: Promise 'Promise()' was not kept.`_
Here's the test:

```python3
class A:
    def __init_subclass__(cls, **kwargs):
        cls.f = dispatch(cls.f)

    def f(self, x: str):
        return x


class B(A):
    def f(self, x: int):
        return x

    @dispatch
    def _(self):
        pass


class MethodOverloadingTests(unittest.TestCase):
    def test_call_overloaded_method(self):
        result = B().f(1)
        self.assertEqual(1, result)
```

**Comment by wesselb** [comment]
Hey @rustrar,

Plum uses `__set_name__` to get a reference to the class containing the method. If you'd be assigning the method manually, as you're doing, you'll need to call that function before the assignment. Here's how that would work in the example:

```python
import unittest

from plum import dispatch

class A:
    def __init_subclass__(cls, **kwargs):
        method = dispatch(cls.f)
        method.__set_name__(cls, None)
        cls.f = method

    def f(self, x: str):
        return x


class B(A):
    def f(self, x: int):
        return x

    @dispatch
    def _(self):
        pass


class MethodOverloadingTests(unittest.TestCase):
    def test_call_overloaded_method(self):
        result = B().f(1)
        self.assertEqual(1, result)
```

I hope to drop this requirement in future version, but currently this is the way it must be done.

**Comment by rustrar** [comment]
Hi, @wesselb!
Thank you for your reply, it works :)

**Comment by wesselb** [comment]
I'm glad to hear that. :) Closing the issue then!
