### ISSUE TITLE
[help wanted] Move documentation to Sphinx+Readthedocs

### ISSUE THREAD

**Issue by PhilipVinc** [wesselb/plum#56]
Help wanted: anyone who wants to pick this up is welcome.

If you setup the sphinx documentation (markdown please) we can take care of readthedocs integration quite easily.

**Comment by wesselb** [comment]
Ah, see also my reply [here]. Would readthedocs be preferable over building the docs with a Github Action and publishing it with Github Pages?

**Comment by tbsexton** [comment]
Documentation has (unofficially?) moved to jupyter book, so presumably this is closable? :smiley:

**Comment by wesselb** [comment]
@tbsexton I think so! Though, maybe we should add a small cute snippet to make the landing page (the README) look a little more appealing?
