### ISSUE TITLE
Naming of args

### ISSUE THREAD

**Issue by reidGP** [wesselb/plum#64]
Hi - this looks like a cool package so just installed to play around with it.

I noticed that the following (dumb / trivial) example does not work for the 2nd pair of print statements (where I supply names for the args). Is there a design reason for this? I like always supplying these so others can understand what my code is doing (i.e. in the example which number is the numerator and which is the denominator, without having to click thru to the function def).

Thanks!

![image](https://user-images.githubusercontent.com/89226537/192380793-3a11eb85-85ae-45fb-873f-f46137fed353.png)

**Comment by wesselb** [comment]
Hey @reidGP! :)

First of all, I'm very sorry for the super slow reponse.

You are right that keyword arguments might not work as expected. This is [described here](https://wesselb.github.io/plum/keyword_arguments.html).

The reason for this design choice is that, fundamentally, multiple dispatch to identifies arguments by their position. This is contrary to keyword arguments, which identifies arguments by names. [Note that it also works this way in the Julia programming language.](https://docs.julialang.org/en/v1/manual/methods/#Note-on-Optional-and-keyword-Arguments)

**Comment by reidGP** [comment]
OK I got it, thanks. Not sure if I missed that in the documentation (if so sorry!) or if it is new but thanks for the clarification

**Comment by wesselb** [comment]
Absolutely no problem. :) That’s what issues are for! Closing this now, but please open another issue if anything else is unclear.

**Comment by cmukesh19** [comment]
I faced this same issue - good that I've read this issue. Else I could be blamed for missing the documentation as well as the previously reported issue 👍

**Comment by wesselb** [comment]
@cmukesh19 Happy to answer additional questions, should you have any :)
