### ISSUE TITLE
"pip install plum" creates a "tests" directory in site-packages

### ISSUE THREAD

**Issue by erezsh** [wesselb/plum#65]
Ideally, each package should create only one folder.

Also, "tests" is a very common name, and this is very likely to collide with local folders.

**Comment by PhilipVinc** [comment]
It's due to the autodiscovery of the package and subpackage.. it's an easy fix

**Comment by wesselb** [comment]
Hey @erezsh! Sorry for the radio silence.

I've amended `setup.py` to exclude `tests` and all subdirectories. Thanks for catching this. :)
