### ISSUE TITLE
Plum 2

### ISSUE THREAD

**Issue by wesselb** [wesselb/plum#68]
### What is This?
This issue proposes possible major improvements for a version two of the package.  The goal is to start a discussion around these proposals. If you agree or disagree with some or all of changes, or think that other improvements are missing, then please do share your thoughts by commenting below. :) Tagging @PhilipVinc, @tbsexton, @leycec, and @seeM here since they have been involved in recent relevant discussions.

None of the proposed changes should change current behaviour, thus maintaining backwards compatibility. I'll be continuously updating and adding to this issue over time.

The list of proposed improvements is as follows:

### Instance-Check-Based Dispatch
Instead of performing dispatch based on the types of the arguments, perform dispatch entirely using `isinstance`, hence fully eliminating the need to use `type_of`. [See this proposal by @tbsexton.](https://github.com/wesselb/plum/issues/53#issuecomment-1274235670) The massive benefit of doing things this way is it becomes _much_ easier to support types like `Literal`s (#66), `Protocol`s (#28), `numpy` arrays with a specific number of dimensions (#10), and `PyTree`s ([Stheno #21](https://github.com/wesselb/stheno/issues/21)).

The big downside of this change is that performance will take a hit, since instance checks will need to happen every time dispatch happens. However, by using @beartype (@leycec), instance checks will be blazingly fast, so the performance hit should be minimal. Moreover, caching is still possible for functions with a so-called _faithful dispatch tree_ ([see here](https://github.com/wesselb/plum/issues/53#issuecomment-1288103843)), so we should get the best of both worlds!

Although dispatch will not rely on `type_of` anymore, other functionality of the package still does, such as [promotion](https://github.com/wesselb/plum/blob/master/plum/promotion.py). Hence, a `type_of` function is still necessary.

### Postponed Evaluation of Types
[@beartype](https://github.com/beartype/beartype/issues/7#issuecomment-1251978495) now includes `beartype.peps.resolve_pep538()`, which should handle PEP538-style postponed types for us. A massive thanks to @leycec for this!! This allows us to get rid of all use of `inspect`, which I believe currently is causing performance issues ([Stheno #25](https://github.com/wesselb/stheno/issues/25)). Deferring the responsibility of handling postponed evaluation of types to @beartype should _significantly_ simplify the internals of the package.

### Wrapping of Types
Internally Plum currently wraps types in its own types. We should get rid of those entirely and use types from `typing`. This does pose a challenge for some more advanced custom types, such as `PromisedType`.

### Compatibility with Modern Tooling
Whatever Plum does should be compatible with modern tooling. Think `mypy`, `pylance` (#51), and possible others.

**Comment by tbsexton** [comment]
Awesome! I'll have to go through a bit more later

As for promotion, isn't that just a baked-in dispatched function? I was checking the code for hard dependencies on a `type_of` kind of functionality, but at first glance it looks like it's a dispatched function anyway, which gets a list of "known" promotion rules.

So theoretically, all of the tree search stuff should still apply? Plum provides some decent default promotions, which the underlying dispatcher can do a lookup on, and users can extend with their own types. 

We don't expect a situation where the promotion function should know what to do with a type that neither the devs or the users have told it about... right?

**Comment by wesselb** [comment]
> As for promotion, isn't that just a baked-in dispatched function?

> So theoretically, all of the tree search stuff should still apply?

Yes, I would agree! My comment in the initial post is more a practical one. Namely, currently the code relies on a function `type_of`. _Most likely_ it can be refactored to eliminate all uses of `type_of`, but I guess that I'm not 100% certain that we can do this until we actually do it.

**Comment by leycec** [comment]
Brilliance personified! As an addendum to #53, I hereby promise that `beartype 0.13.0` (...*so, the next @beartype after the @beartype I hope to publish this weekend*) will implement **deep type-checking** for containers everyone cares about – including dictionaries and sets.

I'll try to remember to post an update here when `beartype 0.13.0` lands. Alternately, we're also tracking progress on deep type-checking at beartype/beartype#167 and beartype/beartype#53. Please throw tomatoes at me there if Plum desperately needs something currently omitted by @beartype.

We now return to your regularly scheduled brilliance. I'm so impressed my mouth is agape. :open_mouth:

**Comment by wesselb** [comment]
Oh hell yeah, that would be _absolutely fantastic_! As always, @leycec, thank you so much for your time and effort spent on @beartype. @beartype is making everyone's lifes nicer. :)

> Please throw tomatoes at me there if Plum desperately needs something currently omitted by https://github.com/beartype.

Will do! 🍅

**Comment by astanziola** [comment]
If I may add something to the whishlist of v2.0 of this amazing project, would be to be able to use automated documentaton (either via sphinx or mkdocstrings).

I have been experimenting a bit bit haven't found a way that doesn't seem like an hack (and maybe there is not one?)

**Comment by astanziola** [comment]
Yes, and probably it makes more sense to develop it separately from `plum`.

At some point I wrote [this to work with mkdocs and plum](https://github.com/astanziola/plumkdocs) and at least [shows the methods](https://ucl-bug.github.io/jwave/api_operators.html), but is one piece of code that I'm particoularly not proud of (it is really, really hacky) and I don't know much about the bits underlying automatic documentation to do it properly.

Anyhow, this is probably not the best place to talk about this, I just wanted to raise the issue :)
Thanks again for this great project!

**Comment by tbsexton** [comment]
Thought I'd add my 2c here... I'm pretty sure this might be somewhat addressed by the various docstring groups already, via `@overload`. It's a "do-nothing" decorator, but shows mypy that a function can have multiple type-signatures. 

I think, if Plum 2 can somehow automatically imply that calling `dispatch` _also implies_ a call to `@overload`, then sphinx and mkdocs both have other solutions already for documentation. 
- https://github.com/sphinx-doc/sphinx/issues/3610
- https://github.com/mkdocstrings/mkdocstrings/issues/308

**Comment by leycec** [comment]
@beartype crew: *combine all your powers!*

There are three API generators of general interest in Python. Technically, there are more (e.g., Twisted's `pydoctor`). Pragmatically, nobody cares about those. What's left is:

* Sphinx's [bundled `autodoc` extension](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). Since both Plum and `autodoc` are runtime-oriented, **Plum should already work out-of-the-box with `autodoc`.** Courtesy official `autodoc` documentation:

> If you document decorated functions or methods, keep in mind that `autodoc` retrieves its docstrings by importing the module and **inspecting the `__doc__` attribute of the given function or method.** That means that if a decorator replaces the decorated function with another, it must copy the original `__doc__` to the new function.

* Sphinx's [third-party `autoapi` extension](https://sphinx-autoapi.readthedocs.io), maintained by Read The Docs (RTD). Since RTD does it *and* since `autodoc` ostensibly *suuuuucks*, everyone and their pet chimera cat-dogs are migrating from `autodoc` to `autoapi`. Unlike `autodoc`, `autoapi` *only* performs static analysis. Problems for Plum start here.
* mkdoc's [`mkdocstring`](https://mkdocstrings.github.io). Like `autoapi`, `mkdocstrings` *only* performs static analysis. Problems for Plum continue here.

`autoapi` and `mkdocstrings` are two pain points possibly warranting Plum-specific plugins. But nobody wants to write, debug, document, and maintain those. Instead, we randomly try the standard `typing`-centric workaround that `autoapi` and `mkdocstrings` will absolutely ignore – because we're on *that* timeline:

```python3
from typing import TYPE_CHECKING, overload

# If somebody is statically analyzing us, reduce Plum's
# @dispatch decorator to the standard @overload decorator.
if TYPE_CHECKING:
    dispatch = overload
# Else, somebody is running us at runtime. In this case,
# define Plum's @dispatch decorator in the standard way.
else:
    from collections.abc import Callable
    from typing import TypeVar
    T = TypeVar('T', bound=Callable)

    def dispatch(T) -> T: ...
```

If either `autoapi` or `mkdocstrings` do *not* currently support `typing.TYPE_CHECKING`, they probably should. I consider that an upstream bug. Upstream should be notified. Blame upstream! I voted for Plum.

**Comment by wesselb** [comment]
@astanziola 

> At some point I wrote [this to work with mkdocs and plum](https://github.com/astanziola/plumkdocs) and at least [shows the methods](https://ucl-bug.github.io/jwave/api_operators.html), but is one piece of code that I'm particoularly not proud of (it is really, really hacky) and I don't know much about the bits underlying automatic documentation to do it properly.

Ahhh, this is nice! Even though it is hacky, the result looks nice and it would be exactly what we're looking for.

> Anyhow, this is probably not the best place to talk about this, I just wanted to raise the issue :) Thanks again for this great project!

Thanks to you for raising the issue! :) You're totally right, and IMO this is something that should be addressed on the short term, if at all possible.

---

@tbsexton @leycec 

> autoapi and mkdocstrings are two pain points possibly warranting Plum-specific plugins. But nobody wants to write, debug, document, and maintain those. Instead, we randomly try the standard typing-centric workaround that autoapi and mkdocstrings will absolutely ignore – because we're on that timeline: `<snipped snippet>`

Ahhh, this is very clever! I've yet to try this, but when I get around to freeing up some time to more closely look into the documentation isssue, this will be the first item on my to-try list. :) It would be very nice if there were a solution that doesn't require writing plugins.
