### ISSUE TITLE
Can we add a link to the docs

### ISSUE THREAD

**Issue by PabloLION** [wesselb/plum#69]
Adding a link of the doc to the "About" section like [usehooks-ts](https://github.com/juliencrn/usehooks-ts) can be easy and helpful for readers.

**Comment by PabloLION** [comment]
![image](https://user-images.githubusercontent.com/36828324/197417451-0a98829b-c76e-4103-b5b4-46efc88a3e35.png)
Like this

**Comment by wesselb** [comment]
Done! Thanks for the suggestion, @PabloLION :)
