### ISSUE TITLE
[BUG] Default arguments are not supported with Dispatch (regression from 0.2.5)

### ISSUE THREAD

**Issue by PhilipVinc** [wesselb/plum#7]
This was working in 0.2.5,

```python
import plum
from plum import dispatch

@dispatch
def test(a:int, b: int = 1):
	print('int, int')

@dispatch
def test(a:float, b: int = 1):
	print('float, int')

In [33]: 

In [33]: test(1,1)
---------------------------------------------------------------------------
NotFoundLookupError                       Traceback (most recent call last)
<ipython-input-33-9b86683066a3> in <module>
----> 1 test(1,1)

~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/plum/function.cpython-38-x86_64-linux-gnu.so in plum.function.Function.__call__()

~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/plum/function.cpython-38-x86_64-linux-gnu.so in plum.function.Function.resolve_method()

~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/plum/function.cpython-38-x86_64-linux-gnu.so in plum.function.Function.resolve_signature()

NotFoundLookupError: For function "test", signature Signature(builtins.int, builtins.int) could not be resolved.

In [34]: test(1)
int, int

```

**Comment by PhilipVinc** [comment]
however without specifying the last argument it works.
```python
f.invoke(type(a1), type(a2))
Out[31]: <cyfunction append at 0x7fa1884ece10>
````

Those methods have all a default third argument, as they are defined like
```python
@dispatch
def append(self: History, val: History, it: Any = None):
    if not set(self.keys()) == set(val.keys()):
        raise ValueError("cannot concatenate MVHistories with different keys")
```

so maybe the problem is there

**Comment by PhilipVinc** [comment]
Indeed.
I updated the post above with a simpler reproducer

**Comment by PhilipVinc** [comment]
ops, indeed this is docuemnted.

However, it was working before...

**Comment by wesselb** [comment]
This might indeed have worked before due to a subtle bug (IIRC). The current defined behaviour is that keyword arguments can be provided but are not dispatched on. The recommended way to set default values is the following pattern:

```python
from plum import dispatch

@dispatch
def test(a: int, b: int):
	print('int, int')

@dispatch
def test(a: int):
	return test(a, 1)
```

The reason to exclude keyword arguments from the dispatch process is mostly simplicity... Perhaps there is a better solution.

**Comment by PhilipVinc** [comment]
I think that excluding kw args from dispatch is ok... Julia indeed does the same.

However for default arguments, that's a bit unfortunate and error prone.

I think that what you could do is... copy Julia again ( see [here](https://docs.julialang.org/en/v1/manual/functions/#Optional-Arguments) ), and make a method with a default argument automatically build another method:
```python
from plum import dispatch

@dispatch
def test(a:int, b:int =3):
   pass
```

would be equivalent to typing
```python
from plum import dispatch

@dispatch
def test(a:int, b:int):
   pass

@dispatch
def test(a:int):
   test(a, 3)
```

This could be automatized easily inside the decorator, no?

**Comment by wesselb** [comment]
You're right. That seems like a relatively easy and handy feature. Actual keyword arguments should then be specified using `*`:

```python
from plum import dispatch

@dispatch
def test(a: int, b_with_default:int = 3, *, c_kw_only = 4):
   pass
```

**Comment by gc-ss** [comment]
Would love to have this!

:+1:

**Comment by wesselb** [comment]
Hey guys!

Just letting you know that I'm a little busy at the moment, but I hope to get to this in the near future.
