### ISSUE TITLE
No way to dispatch based on return type

### ISSUE THREAD

**Issue by TheFGFSEagle** [wesselb/plum#70]
I found it very annoying that I couldn't get the value with the right type from my own property node implementation. Example:
```py
class Node:
  def __init__(self, value):
    self.value = value
  …
  @dispatch
  def getValue(self) -> int:
    return int(self.value)
  
  @dispatch
  def getValue(self) -> bool:
    if str(self.value).lower() == "true":
      return True
    elif str(self.value).lower() == "false":
      return False
    else:
      return bool(self.value)

n = Node("false")
v: int = n.getValue()
print(type(v))
```
which prints `bool` instead of the expected `int`. The type hint of variables is encoded in the namespaces `__annotations__` - any chance of this getting implemented ? :) Thanks in advance !

**Comment by TheFGFSEagle** [comment]
Well, is there a way to force `plum` to call a function / method with a specific signature, by using a wrapper function ? That wouldn't be ideal, but I guess if I need more I ought to be coding in C++ ! ;)

**Comment by wesselb** [comment]
There is, but you need to provide some clue about which method to call to the method.

Below is one way of achieving what you're after. This clearly isn't very pretty, but you can always improve the aesthetics by introducing some syntactic sugar.

```python
from plum import dispatch

class Node:
  def __init__(self, value):
    self.value = value

  @dispatch
  def getValue(self, return_value: int) -> int:
    return int(self.value)
  
  @dispatch
  def getValue(self, return_value: bool) -> bool:
    if str(self.value).lower() == "true":
      return True
    elif str(self.value).lower() == "false":
      return False
    else:
      return bool(self.value)

n = Node("false")
print(n.getValue.invoke(bool)(None))  # False
```
See [the manual](https://wesselb.github.io/plum/advanced_usage.html#directly-invoke-a-method) for an explanation of what `invoke` does.

**Comment by TheFGFSEagle** [comment]
Thanks !
