### ISSUE TITLE
Support for multiple dispatch with constructors

### ISSUE THREAD

**Issue by itsdfish** [wesselb/plum#72]
Thanks for putting this package together. I noticed that multiple dispatch does not work on constructors. Here is a MWE:

```
from plum import dispatch

class MyClass:
    
    @dispatch
    def __init__(self, x: int, y: int):
        self.x = x
        self.y = y
        
MyClass(x=1, y=2)
```

**Comment by wesselb** [comment]
Hey @itsdfish! This should work, as long as the arguments are given as positional arguments instead of positional arguments. That is, `MyClass(1, 2)` should work. :)

**Comment by itsdfish** [comment]
@wesselb, my mistake. Thanks for clarifying. I guess it's easy to forget the distinction given how functions typically work by default.

**Comment by wesselb** [comment]
@itsdfish No problem at all. I agree it’s not entirely obvious. Maybe this can be clarified somewhere…
